# Copyright 2023 Shaun Mitchell

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#  	http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

swagger: '2.0'
info:
  title: airquality
  description: Air Quality Mock API Endpoint
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address:
  path_translation: APPEND_PATH_TO_ADDRESS
securityDefinitions:
   APIKeyQueryParam:
     type: apiKey
     in: query
     name: key
paths:
  "/v1/currentConditions:lookup":
    post:
      operationId: currentConditions.lookup
      security:
        - APIKeyQueryParam: []
      summary: "The Current Conditions endpoint provides hourly air quality information in
        more than 100 countries, up to a 500 x 500 meters resolution."
      consumes:
        - application/json
      parameters:
        - in: body
          name: location
          description: "Required. The longitude and latitude from which the API looks for air quality current conditions data."
          schema:
            type: object
            required:
              - latitude
              - longitude
            properties:
              latitude:
                type: string
              longitude:
                type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              latitude:
                type: string
              longitude:
                type: string