repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: detect-private-key
    - id: check-yaml
      args:
        - --allow-multiple-documents
    - id: trailing-whitespace
